### PR TITLE
I think this is a mispell

### PR DESCRIPTION
**Pull request by ChrisTsou**

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Doesn't seem like it according to this and a few other translators I've tried out http://www.snowcrest.net/donnelly/piglatin.html

Can you explain your reasoning please @ChrisTsou?

**Comment by ChrisTsou** [comment]
I'm an idiot. Because the first test is "banana --> ananabay" i thought you have to reverse the word and add "ay". i now realize you have to put the consonant at the end of the word. English is not my native language that's why i got so confused and realized it after being really confused on the next tests -.-'

**Comment by 105ron** [comment]
No worries @ChrisTsou. Don't be afraid to contribute in the future as we do make mistakes (sometimes ;) ). And good luck with your learning.

**Comment by ChrisTsou** [comment]
On my defence, all tests where passing with just reversing. Up to "counts 'qu' as a single phoneme" :)

**Pull request closed without merging**
